/* config.js — generated by the build. Public settings only: the Supabase anon key is designed to be public. */
window.APP_CONFIG = {
  "slug": "review-analyzer",
  "name": "Review Radar",
  "supabaseUrl": "",
  "supabaseAnonKey": "",
  "aiProxy": "",
  "google": false,
  "prompts": [
    {
      "say": "What is the biggest complaint and when did it start?",
      "does": "Reads the trends and answers with dates."
    },
    {
      "say": "Compare battery feedback between the two products",
      "does": "Opens the comparison and summarizes it."
    },
    {
      "say": "Draft replies to the five worst reviews",
      "does": "Writes replies into the queue."
    }
  ]
};
